Adapta coletor com alteração de Julho de 2019
dadosjusbr/coletor-mpba pull request #4
Opened 2021-11-03 11:56 UTC by joaolgm

Alteração ocorrida em Julho de 2019 foi na maneira de disponibilizar os dados. Foi criado o arquivo de dados Verbas Indenizatorias, mudando algumas colunas do então único arquivo de dados disponibilizado, contracheque.

2021-11-03 12:12 UTC, danielfireman requested changes

2021-11-03 12:12 UTC, danielfireman commented on src/data.py
> +    def validate_2018(self):
A validação não deve incluir o "/output" hardcoded. Deve obter via parâmetro no construtor, o qual deve ser obtido via variável de ambiente.

2021-11-03 12:12 UTC, danielfireman commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Em alguns meses não temos esse detalhamento, certo?

2021-11-03 12:22 UTC, joaolgm commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Temos sim, devido ao arquivo contracheque (que é estável) sempre carregar colunas como gratificação natalina, abono de permanência, função de confiança e férias.

2021-11-03 12:28 UTC, danielfireman commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Tratar do mesmo jeito o detalhamento quanto temos um arquivo com diversas colunas a mais e outro que me parece base, me parece bem ruim.

Gostaria de ouvir @nazareno e @jeffersonrpn nessa. 

Contexto:
- No MPBA temos alguns meses em que o arquivo de detalhamento de indenizações está faltando (mais detalhes #3 )
- Porém o arquivo base da remuneração já dá alguns detalhes, como por exemplo, gratificação natalina e abono permanência

Temos duas interpretações possíveis:
- Essas colunas do arquivo base já são consideradas detalhamento e que o efeito dessa ausência de dados será apenas na diferença das colunas
- As colunas do arquivo base não representam detalhamento das indenizações, apenas quando existe o **arquivo** detalhando as mesmas

2021-11-03 13:57 UTC, nazareno commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Eu acho que se ignorarmos o detalhamento do arquivo base estaremos desperdiçando informações, então sugiro mantermos. Fica mais chato de analisar, mas acho que a outra opção deixa informação faltando, o que é mais grave.

2021-11-03 14:37 UTC, danielfireman commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Opa @nazareno, só deixando super claro, principalmente dado esse comentário:

> Eu acho que se ignorarmos o detalhamento do arquivo base estaremos desperdiçando informações

A ideia não é que a gente ignore as informações que vem do arquivo base e sim, decidir como elas vão se refletir no índice. As informações continuarão sendo armazenadas.

- Na opção 1, `metadados.outras_receitas` seria `DETALHADO` quando o arquivo detalhando as indenizações não existir
- Na opção 2, `metadados.outras_receitas` seria `SUMARIZADO` quando o arquivo detalhando as indenizações não existir

2021-11-04 14:45 UTC, jeffersonrpn commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
@danielfireman Se na opção 1 você quis dizer quando o arquivo EXISTIR, eu acho que faz sentido o metadado classificá-lo como DETALHADO.

2021-11-04 14:47 UTC, danielfireman commented on src/metadado.py
>      metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Isso, @jeffersonrpn, quis dizer quando existir ser detalhado. E quando não existir sumarizado. 

O problema em questão é que o arquivo não existe. Como você acha que devemos proceder?

2021-11-22 15:01 UTC, danielfireman reviewed
Adicionar testes de unidade?

2021-11-22 15:02 UTC, danielfireman commented on src/data.py
> +                output_path + f"/Membros ativos-contracheque-{self.month}-{self.year}.ods"
seguir o padrão na coleta? `membros-ativos-contracheque-10-2018.ods`

2021-11-22 17:22 UTC, danielfireman approved these changes

2021-11-23 11:50 UTC, merged